from django.core.management.base import BaseCommand
from core.models import Survey, SurveyResult
from djangae.db import transaction
from django.db import IntegrityError
from django.utils import timezone
import random


tenant = 'ads'
dmb_d = {
    "organization": 2.1,
    "attribution": 1.6,
    "access": 2.3,
    "ads": 3.7,
    "audience": 0.6,
    "automation": 2.0,
}

dmb = 3.6


company_set_1 = [
    u"rookery",
    u"congregation",
    u"troop ",
    u"shrewdness",
    u"troop ",
    u"flange",
    u"cete",
    u"colony ",
    u"cauldron",
    u"sleuth ",
    u"sloth",
    u"colony ",
    u"family",
    u"sute",
    u"sounder",
    u"obstinacy ",
    u"gang",
    u"caraven",
    u"flock",
    u"train",
    u"clowder",
    u"pounce",
    u"glaring",
    u"destruction",
    u"mob",
    u"coalition",
    u"rag ",
    u"rake",
    u"herd ",
    u"parcel",
    u"pod",
    u"pace",
    u"herd",
    u"parade",
    u"memory",
    u"gang",
    u"tower",
    u"implausibility",
    u"trip",
    u"drove",
    u"herd",
    u"flock",
    u"tribe",
    u"troop ",
    u"band",
    u"array",
    u"thunder ",
    u"bloat",
    u"clan ",
    u"cackle",
    u"prowl ",
    u"shadow",
    u"mob ",
    u"troop",
    u"kindle",
    u"litter",
    u"intrigue",
    u"conspiracy",
    u"leap",
    u"pride ",
    u"sawt",
    u"richness",
    u"labor",
    u"troop ",
    u"barrel",
    u"pack",
    u"span",
    u"barren",
    u"blessing",
    u"raft ",
    u"romp",
    u"drove",
    u"team",
    u"yoke",
    u"embarrassment",
    u"drift",
    u"drove",
    u"sounder",
    u"team",
    u"passel",
    u"pack",
    u"aurora",
    u"celebration",
    u"prickle",
    u"turmoil",
    u"pod",
    u"school",
    u"herd",
    u"colonies ",
    u"coteries",
    u"colony",
    u"nest",
    u"warren",
    u"husk",
    u"down ",
    u"herd",
    u"stubbornness ",
    u"crash",
    u"harem",
    u"bed",
    u"scurry",
    u"dray",
    u"streak ",
    u"ambush",
    u"pod",
    u"gam",
    u"herd",
    u"pack",
    u"route",
    u"wisdom",
    u"herd",
    u"zeal",
    u"dazzle",
]


company_set_2 = [
    u"Aardvark",
    u"Albatross",
    u"Alligator",
    u"Alpaca",
    u"Ant",
    u"Anteater",
    u"Antelope",
    u"Ape",
    u"Armadillo",
    u"Ass/donkey",
    u"Baboon",
    u"Badger",
    u"Barracuda",
    u"Bat",
    u"Bear",
    u"Beaver",
    u"Bee",
    u"Binturong",
    u"Bird",
    u"Bison",
    u"Bluebird",
    u"Boar",
    u"Bobcat",
    u"Buffalo",
    u"Butterfly",
    u"Camel",
    u"Capybara",
    u"Caracal",
    u"Caribou",
    u"Cassowary",
    u"Cat",
    u"Caterpillar",
    u"Cattle",
    u"Chameleon",
    u"Chamois",
    u"Cheetah",
    u"Chicken",
    u"Chimpanzee",
    u"Chinchilla",
    u"Chough",
    u"Coati",
    u"Cobra",
    u"Cockroach",
    u"Cod",
    u"Cormorant",
    u"Cougar",
    u"Coyote",
    u"Crab",
    u"Crane",
    u"Cricket",
    u"Crocodile",
    u"Crow",
    u"Cuckoo",
    u"Curlew",
    u"Deer",
    u"Degu",
    u"Dhole",
    u"Dingo",
    u"Dinosaur",
    u"Dog",
    u"Dogfish",
    u"Dolphin",
    u"Donkey",
    u"Dotterel",
    u"Dove",
    u"Dragonfly",
    u"Duck ",
    u"Dugong",
    u"Dunlin",
    u"Eagle",
    u"Echidna",
    u"Eel",
    u"Eland",
    u"Elephant",
    u"Elephant seal",
    u"Elk (wapiti)",
    u"Emu",
    u"Falcon",
    u"Ferret",
    u"Finch",
    u"Fish",
    u"Flamingo",
    u"Fly",
    u"Fox",
    u"Frog",
    u"Gaur",
    u"Gazelle",
    u"Gecko",
    u"Gerbil",
    u"Giant panda",
    u"Giraffe",
    u"Gnat",
    u"Gnu",
    u"Goat",
    u"Goldfinch",
    u"Goosander",
    u"Goose",
    u"Gorilla",
    u"Goshawk",
    u"Grasshopper",
    u"Grouse",
    u"Guanaco",
    u"Guinea fowl",
    u"Guinea pig",
    u"Gull",
    u"Hamster",
    u"Hare",
    u"Hawk",
    u"Hedgehog",
    u"Hermit crab",
    u"Heron",
    u"Herring",
    u"Hippopotamus",
    u"Hoatzin",
    u"Hoopoe",
    u"Hornet",
    u"Horse",
    u"Human",
    u"Hummingbird",
    u"Hyena",
    u"Ibex",
    u"Ibis",
    u"Iguana",
    u"Impala",
    u"Jackal",
    u"Jaguar",
    u"Jay",
    u"Jellyfish",
    u"Jerboa",
    u"Kangaroo",
    u"Kingfisher",
    u"Kinkajou",
    u"Koala",
    u"Komodo dragon",
    u"Kookaburra",
    u"Kouprey",
    u"Kudu",
    u"Lapwing",
    u"Lark",
    u"Lemur",
    u"Leopard",
    u"Lion",
    u"Lizard",
    u"Llama",
    u"Lobster",
    u"Locust",
    u"Loris",
    u"Louse",
    u"Lynx",
    u"Lyrebird",
    u"Macaque",
    u"Macaw",
    u"Magpie",
    u"Mallard",
    u"Mammoth",
    u"Manatee",
    u"Mandrill",
    u"Marmoset",
    u"Marmot",
    u"Meerkat",
    u"Mink",
    u"Mole",
    u"Mongoose",
    u"Monkey",
    u"Moose",
    u"Mosquito",
    u"Mouse",
    u"Myna",
    u"Narwhal",
    u"Newt",
    u"Nightingale",
    u"Nine",
    u"Octopus",
    u"Okapi",
    u"Opossum",
    u"Oryx (gemsbok)",
    u"Ostrich",
    u"Otter",
    u"Owl",
    u"Oyster",
    u"Panther",
    u"Parrot",
    u"Panda",
    u"Partridge",
    u"Peafowl",
    u"Pelican",
    u"Penguin",
    u"Pheasant",
    u"Pig ",
    u"Pigeon",
    u"Pika",
    u"Polar bear",
    u"Pony",
    u"Porcupine",
    u"Porpoise",
    u"Prairie dog",
    u"Pug",
    u"Quail",
    u"Quelea",
    u"Quetzal",
    u"Rabbit",
    u"Raccoon",
    u"Ram",
    u"Rat",
    u"Raven",
    u"Red deer",
    u"Red panda",
    u"Reindeer (caribou)",
    u"Rhea",
    u"Rhinoceros",
    u"Rook",
    u"Salamander",
    u"Salmon",
    u"Sand dollar",
    u"Sandpiper",
    u"Sardine",
    u"Sea lion",
    u"Seahorse",
    u"Seal",
    u"Shark",
    u"Sheep ",
    u"Shrew",
    u"Siamang",
    u"Skunk",
    u"Sloth",
    u"Snail",
    u"Snake",
    u"Spider",
    u"Squid",
    u"Squirrel",
    u"Starling",
    u"Stegosaurus",
    u"Swan",
    u"Tamarin",
    u"Tapir",
    u"Tarsier",
    u"Termite",
    u"Tiger",
    u"Toad",
    u"Toucan",
    u"Turaco",
    u"Turkey",
    u"Turtle",
    u"Vicuna",
    u"Vinegaroon",
    u"Viper",
    u"Vulture",
    u"Wallaby",
    u"Walrus",
    u"Wasp",
    u"Water buffalo",
    u"Waxwing",
    u"Weasel",
    u"Whale",
    u"Wobbegong",
    u"Wolf",
    u"Wolverine",
    u"Wombat",
    u"Woodpecker",
    u"Worm",
    u"Wren",
    u"Yak",
    u"Zebra",
]

company_set_3 = [
    u"corp.",
    u"inc.",
    u"co.",
    u"ltd.",
]


def create_surveys(quantity):
    for i in range(quantity):
        with transaction.atomic(xg=True):
            company_name = '{} {} {}'.format(
                random.choice(company_set_1).title(),
                random.choice(company_set_2).lower(),
                random.choice(company_set_3).lower()
            )
            try:
                survey = Survey.objects.create(company_name=company_name.decode('utf-8'), tenant=tenant, country='IT', industry='edu')
                result = SurveyResult.objects.create(
                    survey=survey,
                    dmb=dmb,
                    dmb_d=dmb_d,
                    started_at=timezone.now(),
                    response_id='R_xxxxx{}'.format(random.randint(0, 100000))
                )
                survey.last_survey_result = result
                survey.save()
                print("Company:  {}  created".format(company_name.encode('utf-8')))
            except IntegrityError:
                pass


class Command(BaseCommand):
    help = 'Create a number of dummy surveys'

    def add_arguments(self, parser):
        parser.add_argument('quantity')

    def handle(self, *args, **options):
        quantity = int(options['quantity'])
        create_surveys(quantity)
